{% set name = "tesserocr" %}
{% set version = "2.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3bca978dae9e03a327414d3da86954a943233a5169e25aaef14cddbb791d435a

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win and py==27]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - tesseract
    - cython
    - python
    - pip
  run:
    - python
    - {{ pin_compatible('tesseract', max_pin='x.x') }}
    - leptonica  # [not win]
    - pillow

test:
    imports:
        - tesserocr

about:
  home: https://github.com/sirfz/tesserocr
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple, Pillow-friendly, Python wrapper around tesseract-ocr API using Cython
  doc_url: https://github.com/sirfz/tesserocr
  dev_url: https://github.com/sirfz/tesserocr

extra:
  recipe-maintainers:
    - Chilipp
    - sirfz
