{% set name = "tesserocr" %}
{% set version = "2.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44c1c4ef7bdc286cfa144ce1a097e81c3329f4a43509bc8494a1ab852338c6e1

build:
  number: 0
  skip: true  # [win and py==27]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - tesseract
    - cython
    - python
    - pip
  run:
    - python
    - {{ pin_compatible('tesseract', max_pin='x.x') }}
    - leptonica  # [not win]
    - pillow

test:
  imports:
    - tesserocr

about:
  home: https://github.com/sirfz/tesserocr
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple, Pillow-friendly, Python wrapper around tesseract-ocr API using Cython
  doc_url: https://github.com/sirfz/tesserocr
  dev_url: https://github.com/sirfz/tesserocr

extra:
  recipe-maintainers:
    - Chilipp
    - sirfz
