{% set name = "tesserocr" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3744c5c8bbabf18172849c7731be00dc2e5e44f8c556d37c850e788794ae0af4

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - pkg-config
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - setuptools
  host:
    - tesseract
    - cython
    - python
    - pip
    - setuptools
  run:
    - python
    - {{ pin_compatible('tesseract', max_pin='x.x') }}
    - leptonica  # [not win]
    - pillow

test:
  imports:
    - tesserocr

about:
  home: https://github.com/sirfz/tesserocr
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple, Pillow-friendly, Python wrapper around tesseract-ocr API using Cython
  doc_url: https://github.com/sirfz/tesserocr
  dev_url: https://github.com/sirfz/tesserocr

extra:
  recipe-maintainers:
    - Chilipp
    - sirfz
    - jonashaag
